site_name: DiscordKt
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
theme: 
    name: material
    logo: images/discordkt-logo.png
    palette:
        scheme: slate
        primary: cyan
        accent: cyan
